### ISSUE TITLE
Update: Date structure and I\O Function

### ISSUE THREAD

**Issue by lxrzlyr** [lxrzlyr/GAL-DAWN#42]
Some of MTX files could not input correctly, a little probability.
Date structure of Graph need to be optimized.

**Comment by kkie02** [comment]
Keeping to solve this problem.

**Comment by lxrzlyr** [comment]
Some finished in https://github.com/ining7/DAWN-An-Noval-SSSP-APSP-Algorithm/pull/43

**Comment by lxrzlyr** [comment]
Finished in https://github.com/ining7/GAL-DAWN/pull/45
